# Extjs project name that goes to Ext.defaine('#{project_name}'.store.SomeStore')
project_name: eUni

# relative from extgen_config.yml to extjs app directory
# example:
# path_to_ext_app: src/main/webapp/app/
path_to_ext_app: src/main/webapp/app/